name: ALL-USE CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'src/agents/all_use/**'
      - 'src/agent_core/**'
      - 'src/shared_modules/**'
      - 'deployment/all_use/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/agents/all_use/**'
      - 'src/agent_core/**'
      - 'src/shared_modules/**'
      - 'deployment/all_use/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build ALL-USE package
        run: |
          echo "Building ALL-USE agent package"
          # Package-specific build commands would go here
          mkdir -p dist/all_use
          cp -r src/agent_core dist/all_use/
          cp -r src/shared_modules dist/all_use/
          cp -r src/agents/all_use dist/all_use/agents/
          cp src/main.py dist/all_use/
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: all-use-build
          path: dist/all_use

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-use-build
          path: dist/all_use
      - name: Run ALL-USE tests
        run: |
          echo "Running ALL-USE agent tests"
          pytest tests/agents/all_use/ tests/agent_core/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy from main branch
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: all-use-build
          path: dist/all_use
      - name: Deploy ALL-USE agent
        run: |
          echo "Deploying ALL-USE agent to target environment"
          # Deployment commands would go here
          # This could include Docker build and push, cloud deployment, etc.
      - name: Notify deployment status
        run: |
          echo "ALL-USE agent deployment completed"
          # Notification commands would go here
